config/routes.rb
Rails.application.routes.draw do  
  
  root 'user#dashboard'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/dashboard' => 'user#dashboard', :as => 'user_dashboard'
  resources :user
  resources :announcements
  resources :documents, only: [:index, :new, :create, :destroy, :update]
  

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
	belongs_to :users
	mount_uploader :attachment, AttachmentUploader
	validates :file_name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :documents
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @announcement = Announcement.find(params[:id])
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:announcement)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
  	@documents = Document.all
  end

  def new
  	@document = Document.new
  end

  def create
  	@document = Document.new(docu_params)
    @document.users_id = current_user.id
    @document.document_type = params[:document][:document_type]
    @document.number_of_copies = params[:document][:number_of_copies]
    @document.page_range = params[:document][:page_range]
    @document.size = params[:document][:size]
    @document.orientation = params[:document][:orientation]
    @document.color = params[:document][:color]
    @document.note = params[:document][:note]
    
  	if @document.save
  		redirect_to user_dashboard_path, notice: "The document #{@document.file_name} has been uploaded."
  	else
  		render "new"
  	end
  end

  def destroy
  	@document = Document.find(params[:id])
  	@document.destroy
  	redirect_to user_dashboard_path, notice: "The document #{@document.file_name} has been destroyed."
  end

  def update
    @document = Document.find(params[:id])
    @user = User.find(@document.users_id)

    if params[:document][:option] == 'print'
      @document.price = params[:document][:price]
      @document.print_status = 'printed'
      @user.accountability += @document.price

    elsif params[:document][:option] == 'transaction'     
      if params[:document][:transaction_status] == 'unpaid'
        @document.transaction_status = 'paid'
        @user.accountability -= @document.price
      else
        @document.transaction_status = 'unpaid'
        @user.accountability += @document.price
      end
    end

    @document.save
    @user.save
    redirect_to user_dashboard_path
  end
  
  private
  	def docu_params
  		params.require(:document).permit(:file_name, :attachment, :number_of_pages, :size, :document_type, :number_of_copies, :page_range, :orientation, :color)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if logged_in?
			redirect_to user_dashboard_path
		end
	end

	def create
		@user = User.find_by(user_id: params[:session][:user_id])
		if @user && @user.password == params[:session][:password]
			log_in @user
			redirect_to user_dashboard_path
		else
			flash.now[:danger] = 'Invalid student number/password!'
			render 'new'
		end
	end
	def destroy
		log_out
		redirect_to login_path
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def dashboard
		@announcements = Announcement.all
		@documents = Document.all
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
	def find_user user_document_id
		@user = User.find(user_document_id).user_id
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.user_id
	end

	def current_user
		@current_user ||= User.find_by(user_id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(session[:user_id])
		reset_session
		@current_user = nil
	end

	def is_admin?
		if logged_in?
			return @current_user.user_id == 'admin'
		else
			return false
		end
	end

	def is_owner? document_id
		if logged_in?
			return @current_user.id == document_id
		else
			return false
		end
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :announcement %><br>
    <%= f.text_field :announcement %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Announcements</h2>

<table>
  <thead>
    <tr>
      <th>Announcement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.announcement %></td>

      <% if logged_in? %>
        <% if current_user.user_id == 'admin' %>
          <td><%= link_to 'Show', announcement %></td>
          <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
          <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if logged_in? %>
  <% if current_user.user_id == 'admin' %>
    <%= link_to 'New Announcement', new_announcement_path, class: 'btn btn-info' %>
  <% end %>
<% end %>

<%= link_to 'Back', user_dashboard_path, class: 'btn btn-info' %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Announcement:</strong>
  <%= @announcement.announcement %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<% if logged_in? %>
   <% if current_user.user_id != 'admin' %>
      <button class="btn btn-primary"> <%= link_to "Upload Document", new_document_path %> </button>
   <% end %>
<% end %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>File Name</th>
         <th>Number of Pages to be printed</th>
         <th>Size
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @documents.each do |docu| %>
         <tr>
            <td><%= docu.file_name %></td>
            <td><%= docu.number_of_pages %></td>

         <% if logged_in? %>
            <% if current_user.user_id == 'admin' %>
            <td><%= button_to "Print" %></td>
            <% end %>

            <% if current_user.id == docu.users_id || current_user.user_id == 'admin' %>
            <td><%= button_to "Delete",  docu, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{docu.file_name}?" %></td>
            <% end %>
         <% end %>
         </tr>
         
      <% end %>
   </tbody>
</table>

<%= link_to 'Back', user_dashboard_path, class: 'btn btn-info' %>

app/views/documents/new.html.erb
<% if !@document.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @document.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<%= form_for @document, html: { multipart: true } do |f| %>

<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#uploadModal"> Upload a file </button>

<div class="panel-info">
   <div class="panel-heading">General Specifications</div>
   <div class="panel-body">
      <div class="input-group col-xs-4">
         <span class="input-group-addon">Document type </span>
         <%= f.text_field :document_type %>
      </div>
      <div class="input-group col-xs-4">
         <span class="input-group-addon">Number of copies </span>
         <%= f.text_field :number_of_copies %>
      </div>
      <div class="input-group col-xs-4">
         <span class="input-group-addon">Page range</span>
         <%= f.text_field :page_range %>
      </div>
      <div>
         <div class="input-group col-xs-4">
          <span class="input-group-addon">Paper Size</span>
          <%= f.text_field :size %>
         </div>
         <div class="input-group col-xs-4">
          <span class="input-group-addon">Orientation</span>
          <%= f.text_field :orientation %>
         </div>
         <div class="input-group col-xs-4">
          <span class="input-group-addon">Paper color(Colored or Grayscale)</span>
          <%= f.text_field :color %>
         </div>
      </div>
   </div>
</div>
<div class="panel-info">
   <div class="panel-heading">Additional Specifications</div>
   <div class="panel-body">
     <h1>If PPT</h1>
      <div class="input-group col-xs-4">
      <span class="input-group-addon"> Number of slides per page </span>
        <%= f.text_field :slide_layout %>
   </div> 
   <h1>If PDF</h1>
     <div class="input-group col-xs-4">
       <span class="input-group-addon">Number of pages per paper</span>
       <%= f.text_field :pages_per_paper %>
     </div>
      <div>
      <%= f.text_area :note %>
      </div>
      <div>
      <%= f.submit "Add to Print Queue", class: "btn btn-info" %>
      </div>
   </div>
</div>

<div id="uploadModal" class="modal fade" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
            <h4 class="modal-title">Print Specifications</h4>
         </div>

         <div class="modal-body">
            <!-- <div class="jumbotron"> -->
               <div class="form-group">
                     <%= f.label :file_name %>
                     <%= f.text_field :file_name, class:"form-control" %>
                  
                  <div class="form-group">
                     <input type="file" name="document[attachment]" id="document_attachment" class="file" style="visibility: hidden;position: absolute;">
                     <div class="input-group col-xs-12">
                        <input type="text" class="form-control input-lg" disabled placeholder="Choose File">
                        <span class="input-group-btn">
                           <button class="browse btn btn-primary input-lg" type="button"></i> Browse</button>
                        </span>
                     </div>
                  </div>

               </div>
            <!-- </div> -->
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>

<script type="text/javascript">
   $(document).on('click', '.browse', function(){
  var file = $(this).parent().parent().parent().find('.file');
  file.trigger('click');
});
$(document).on('change', '.file', function(){
  $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
});
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TlrcWebX</title>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="/assets/application.js" type="text/javascript"></script>
  <%= yield :head %>
</head>
<body>

  <% if logged_in? %>
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color: #d9edf7;border: none;">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand"> Hello, <%= current_user.user_id =%> </a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if !is_admin? %>
          <li class="navbar-text">Accountability: <%= current_user.accountability %></li>
          <% end %>
          <li><%= link_to "Log out", logout_path %></li>
        </ul>
      </div>
    </nav>
  <% end %>

  <div class="container" style="padding-top:100px;">
    <%= yield %>
  </div>
</body>
</html>

app/views/user/dashboard.html.erb
<% if !logged_in? %>
  <button> <%= link_to "Log in", login_path %> </button>
<% end %>

<style type="text/css">
  .quotes {
    display: none;
  }
</style>

<table>
  <thead>
    <tr>
      <th><h1>Announcements</h1></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td>
          <h4 class="<%= 'quotes' if !is_admin? %>">
            <%= announcement.announcement %>
          </h4>
        </td>
        
      <% if logged_in? %>
        <% if is_admin? %>
          <td><%= link_to 'Show', announcement %></td>
          <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
          <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
      </tr>
    <% end %>
    <!-- diri pa ini nadara na will_paginate //ajax pa huhu -->
    <%# will_paginate @announcements %>
  </tbody>
</table>

<% if logged_in? %>
  <% if is_admin? %>
  <%= link_to 'New Announcement', new_announcement_path, class: 'btn btn-info' %>
  <% end %>
<% end %>

<%# link_to 'Show All Announcements', announcements_path %>

<br />
<br />
<hr>
<br />

<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<% if logged_in? %>
  <% if !is_admin? %>
  <%= link_to "Upload Document", new_document_path, class: "btn btn-info" %>
  <br />
  <br />

  <% end %>
<% end %>

<% if !is_admin? %>
<table class = "table table-bordered table-striped info">
  <thead> <h1> My Documents </h1> 
   <tr>
     <th> File Name</th>
     <th> Amount to pay </th>
     <th> Print status </th>
     <th> Transaction status </th>
     <th> Actions </th>
   </tr>
  </thead>
   <tbody>
      <% @documents.each do |docu| %>
         <tr>
           <% if is_owner? docu.users_id %>
           <td><%= link_to docu.file_name, asset_path("#{docu.attachment}", target: "_blank") %></td>
           <td><%= docu.price %></td>
           <td><%= docu.print_status %></td>
           <td><%= docu.transaction_status %></td>
            <td><%= button_to "Delete",  docu, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{docu.file_name}?" %></td>
           <% end %>
          </tr>
      <% end %>
   </tbody>
</table> 
<% end -%>

<table class = "table table-bordered table-striped info">
   <thead> <h1> Print Queue </h1>
      <tr>
        <% if is_admin? %>
         <th> Student Number </th>
         <th> File Name</th>
         <th> Document type </th>
         <th> Number of copies </th>
         <th> Size </th>
         <th> Orientation </th>
         <th> Page range </th>
         <th> Color </th>
         <th> (PPT) Number of slides per page </th>
         <th> (PDF) Number of pages per paper </th>
         <th> Amount to pay </th>
         <th> Print status </th>
         <th> Transaction status </th>
         <th> Note </th>

         <% else %>
         <th> File Name</th>
         <th> Print status </th>
         <% end %>
      </tr>
   </thead>
   
   <tbody>
      <% @documents.each do |docu| %>
         <tr>
           <% if is_admin? %>
            <td><%= find_user docu.users_id %></td>
            <td><%= link_to docu.file_name, asset_path("#{docu.attachment}", target: "_blank") %></td>
            <td><%= docu.document_type %></td>
            <td><%= docu.number_of_copies %></td>
            <td><%= docu.size %></td>
            <td><%= docu.orientation %></td>
            <td><%= docu.page_range %></td>
            <td><%= docu.color %> </td>
            <td><%= docu.slide_layout %></td>
            <td><%= docu.pages_per_paper %></td>
            
            <%= form_for docu, html: { multipart: true } do |f| %>
            <%= f.hidden_field :option, :value => 'print' %>
            <%= f.hidden_field :print_status, :value => docu.print_status %>
            <td class="input-group col-xs-2"><%= f.number_field :price, step: :any, :value => docu.price %></td>
            <td><%= f.submit :value => docu.print_status, class: "btn btn-primary" %></td>
            <% end %>

            <%= form_for docu, html: { multipart: true } do |f| %>
            <%= f.hidden_field :docu_id, :value => docu.id %>
            <%= f.hidden_field :option, :value => 'transaction' %>
            <%= f.hidden_field :transaction_status, :value => docu.transaction_status %>
            <td><%= f.submit :value => docu.transaction_status, class: "btn btn-primary" %></td>
            <td><%= docu.note %></td>
            <% end %>

           <% else %>
            <td><%= docu.file_name %></td>
            <td><%= docu.print_status %></td>
           <% end %>
         </tr>
      <% end %>
   </tbody>
</table>

<script type="text/javascript">
  (function() {

    var quotes = $(".quotes");
    var quoteIndex = -1;
    
    function showNextQuote() {
        ++quoteIndex;
        quotes.eq(quoteIndex % quotes.length)
            .fadeIn(2000)
            .delay(2000)
            .fadeOut(2000, showNextQuote);
    }
    
    showNextQuote();
    
})();
</script>

<%# link_to 'Show All Files', documents_path %>